export { default as HeroSection } from "./HeroSection";
export { default as BreedsSection, BREEDS } from "./BreedsSection";
export { default as CtaBannerSection } from "./CtaBannerSection";
export { default as SuppliersSection, SUPPLIERS } from "./SuppliersSection";
export { default as FeaturedCattleSection, PREMIUM_LISTINGS } from "./FeaturedCattleSection";
export { default as ConsultationSection } from "./ConsultationSection";
export { default as RegionsSection, REGIONS } from "./RegionsSection";
export { default as HowWeWorkSection } from "./HowWeWorkSection";
export { default as PrimarySellersSection } from "./PrimarySellersSection";
export { default as BlogSection, BLOGS } from "./BlogSection";
